version: '3.9'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: a8s45d18
      MYSQL_USER: docker
      MYSQL_PASSWORD: a8s45d18
      MYSQL_DATABASE: syncgym
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - syncgym-network
  api:
    image: gastawny/syncgym-api
    restart: always
    build: ../api
    working_dir: /api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/syncgym
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: a8s45d18
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - syncgym-network
networks:
  syncgym-network:
    driver: bridge