CREATE TABLE IF NOT EXISTS `workouts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) UNIQUE,
  `duration` TINYINT NOT NULL,
  `difficulty` TINYINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
