insert into `exercises` (`target_muscle_group_id`, `name`, `difficulty`, `description`) values
    (1, 'Supino', 3, 'Levante de peso deitado em um banco horizontal'),
    (1, 'Flexão de Braço', 2, 'Flexão de braço no chão'),
    (1, 'Fly Declinado', 3, 'Levantamento de peso deitado em banco declinado'),
    (1, 'Crossover', 2, 'Cruzamento de cabos em posição elevada'),
    (2, 'Barra Fixa', 3, 'Levantamento do corpo na barra fixa'),
    (2, 'Remada', 2, 'Puxada de peso na direção do tronco'),
    (2, 'Pulldown', 2, 'Puxada de peso na polia alta'),
    (2, 'Remada Unilateral', 3, 'Puxada de peso com halteres em uma mão'),
    (3, 'Prancha Abdominal', 2, 'Manter posição de prancha no chão'),
    (3, 'Crunch', 1, 'Contração abdominal com elevação do tronco'),
    (3, 'Leg Raise', 2, 'Elevação das pernas estendidas no solo'),
    (3, 'Russian Twist', 1, 'Giro do tronco com peso lateral'),
    (4, 'Desenvolvimento', 3, 'Levantamento de peso acima da cabeça'),
    (4, 'Elevação Lateral', 2, 'Elevação dos braços na lateral do corpo'),
    (4, 'Arnold Press', 3, 'Combinação de rotação e elevação dos braços'),
    (4, 'Face Pull', 2, 'Puxada de peso na altura do rosto'),
    (5, 'Agachamento', 3, 'Flexão dos joelhos como se estivesse sentando'),
    (5, 'Elevação de Quadril', 2, 'Levantamento do quadril no solo'),
    (5, 'Cadeira Abdutora', 2, 'Movimento de abertura das pernas sentado'),
    (5, 'Afundo', 3, 'Passo largo com flexão dos joelhos'),
    (6, 'Gêmeos em Pé', 2, 'Elevação do corpo na ponta dos pés'),
    (6, 'Saltos', 1, 'Saltos verticais para trabalhar a panturrilha'),
    (6, 'Elevação Unilateral', 2, 'Elevação de uma perna por vez'),
    (6, 'Panturrilha Sentado', 2, 'Elevação de peso com as pernas estendidas'),
    (7, 'Encolhimento de Ombros', 2, 'Elevação dos ombros com peso'),
    (7, 'Remada Alta', 3, 'Puxada de peso na direção do pescoço'),
    (7, 'Encolhimento com Barra', 2, 'Encolhimento de ombros com barra'),
    (7, 'Face Pull', 2, 'Puxada de peso na altura do rosto'),
    (8, 'Rosca Direta', 2, 'Flexão dos braços com barra ou halteres'),
    (8, 'Martelo', 2, 'Flexão dos braços com halteres em posição neutra'),
    (8, 'Concentrado', 2, 'Flexão dos braços apoiado em um banco'),
    (8, 'Rosca Inversa', 2, 'Flexão dos braços com pegada invertida'),
    (9, 'Tríceps Pulley', 2, 'Extensão dos braços com polia alta'),
    (9, 'Fundos', 3, 'Flexão de braço com o tronco inclinado para trás'),
    (9, 'Tríceps Corda', 2, 'Extensão dos braços com corda na polia'),
    (9, 'Supino Fechado', 3, 'Levantamento de peso com pegada mais fechada'),
    (10, 'Agachamento Livre', 3, 'Flexão dos joelhos com barra nas costas'),
    (10, 'Leg Press', 2, 'Empurrar peso com os pés em máquina específica'),
    (10, 'Cadeira Extensora', 2, 'Extensão de pernas sentado'),
    (10, 'Afundo', 3, 'Passo largo com flexão dos joelhos'),
    (11, 'Stiff', 3, 'Flexão do tronco mantendo as pernas estendidas'),
    (11, 'Flexor Sentado', 2, 'Flexão de pernas sentado'),
    (11, 'Mesa Flexora', 2, 'Flexão de pernas em posição deitada'),
    (11, 'Cadeira Flexora', 2, 'Flexão de pernas sentado'),
    (12, 'Adutor em Máquina', 2, 'Movimento de fechamento das pernas em máquina'),
    (12, 'Abdução de Quadril', 1, 'Movimento lateral de pernas em máquina'),
    (12, 'Agachamento Lateral', 1, 'Movimento lateral das pernas'),
    (12, 'Afundo Lateral', 1, 'Afundo lateral para trabalhar os abdutores'),
    (13, 'Abdutor em Máquina', 2, 'Movimento de abertura das pernas em máquina'),
    (13, 'Afundo Lateral', 1, 'Afundo lateral para trabalhar os abdutores'),
    (13, 'Abdução de Quadril', 1, 'Movimento lateral de pernas em máquina'),
    (13, 'Agachamento Lateral', 1, 'Movimento lateral das pernas');
